/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SewaAlatRouteImport } from './routes/sewa-alat'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as JasaSurveyorRouteImport } from './routes/jasa-surveyor'
import { Route as IndexRouteImport } from './routes/index'

const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SewaAlatRoute = SewaAlatRouteImport.update({
  id: '/sewa-alat',
  path: '/sewa-alat',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const JasaSurveyorRoute = JasaSurveyorRouteImport.update({
  id: '/jasa-surveyor',
  path: '/jasa-surveyor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jasa-surveyor': typeof JasaSurveyorRoute
  '/kontak': typeof KontakRoute
  '/sewa-alat': typeof SewaAlatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang-kami': typeof TentangKamiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jasa-surveyor': typeof JasaSurveyorRoute
  '/kontak': typeof KontakRoute
  '/sewa-alat': typeof SewaAlatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang-kami': typeof TentangKamiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jasa-surveyor': typeof JasaSurveyorRoute
  '/kontak': typeof KontakRoute
  '/sewa-alat': typeof SewaAlatRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang-kami': typeof TentangKamiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jasa-surveyor'
    | '/kontak'
    | '/sewa-alat'
    | '/sitemap.xml'
    | '/tentang-kami'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/jasa-surveyor'
    | '/kontak'
    | '/sewa-alat'
    | '/sitemap.xml'
    | '/tentang-kami'
  id:
    | '__root__'
    | '/'
    | '/jasa-surveyor'
    | '/kontak'
    | '/sewa-alat'
    | '/sitemap.xml'
    | '/tentang-kami'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JasaSurveyorRoute: typeof JasaSurveyorRoute
  KontakRoute: typeof KontakRoute
  SewaAlatRoute: typeof SewaAlatRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TentangKamiRoute: typeof TentangKamiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sewa-alat': {
      id: '/sewa-alat'
      path: '/sewa-alat'
      fullPath: '/sewa-alat'
      preLoaderRoute: typeof SewaAlatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jasa-surveyor': {
      id: '/jasa-surveyor'
      path: '/jasa-surveyor'
      fullPath: '/jasa-surveyor'
      preLoaderRoute: typeof JasaSurveyorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JasaSurveyorRoute: JasaSurveyorRoute,
  KontakRoute: KontakRoute,
  SewaAlatRoute: SewaAlatRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TentangKamiRoute: TentangKamiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
